### ISSUE TITLE
ceph mon fails to start (fuel 3.2, centos)

### ISSUE THREAD

**Issue by ghost** [Mirantis/fuel#784]
Deploying Fuel 3.2 w/ CentOS (3 controller/OSD nodes) has consistently failed.  The first controller completes without issue while the second and third fail when Puppet tries to start the ceph mon process. Attempting to start ceph mon by hand fails with an error message that public_network is not set in ceph.conf. Manually adding public_network in ceph.conf allows the process to be started.

If I wait for ceph.conf to be created on the first node and quickly add the public_network (and I also specified cluster_network) the setting is propogated to the other two nodes and the deploy completes successfully.

My servers have four untagged network interfaces: management, 192.168.0; storage, 192.168.1; public, 172.16.0; and admin, 172.16.1. Ceph is enabled in settings for volumes, images, and radosgw. Neutron w/ GRE networking is selected. I believe all other settings are left default.

**Comment by xarses** [comment]
You need https://review.openstack.org/#/c/52850/ which should resolve your issue.

**Comment by ghost** [comment]
Thanks; I've applied the patch to our Fuel server for our next deployment.

**Comment by ghost** [comment]
As expected that fixed the problem.  The ceph.conf file got the network values and ceph started.  Thanks.

(Unfortunately, my deployment failed for a different reason.  (While Puppet was deploying OpenStack on the 4 compute nodes, the 3 controller nodes all assumed the same IP address.))
